module = "Policy"
desc = "this is our privacy policy, it may contain what you need"

[[pages]]
naming = "general_privacy_statment_zh"
title = "iTrans通用隐私政策"
desc = "通用隐私政策"
authors = [
    "Offical"
]

[[pages]]
naming = "general_privacy_statment_en"
title = "iTrans general privacy statment"
desc = "general privacy statment"
authors = [
    "Offical"
]

